#!/usr/bin/env bash
# .devcontainer/postCreate.sh
#
# Runs automatically after the dev container is created (postCreateCommand).
# Idempotent — safe to re-run at any time.
#
# Steps:
#   1. Write .env from devcontainer defaults (if .env doesn't already exist)
#   2. Wait for PostgreSQL to be ready
#   3. Run all pending SQLx migrations
#   4. Seed the database with representative development data
#   5. Install Node dependencies for the frontend and SDKs

set -euo pipefail

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

info()    { echo -e "${CYAN}[devcontainer]${NC} $*"; }
success() { echo -e "${GREEN}[devcontainer]${NC} ✓ $*"; }
warn()    { echo -e "${YELLOW}[devcontainer]${NC} ⚠ $*"; }
error()   { echo -e "${RED}[devcontainer]${NC} ✗ $*" >&2; }

WORKSPACE="/workspaces/SorobanPulse"
cd "$WORKSPACE"

# ── 1. Bootstrap .env ─────────────────────────────────────────────────────────
if [ ! -f .env ]; then
  info "Creating .env from devcontainer defaults…"
  cat > .env <<'EOF'
# ── Dev Container environment ─────────────────────────────────────────────────
# Auto-generated by .devcontainer/postCreate.sh
# Edit freely — this file is gitignored.

DATABASE_URL=postgres://soroban:soroban@db:5432/soroban_pulse
STELLAR_RPC_URL=https://soroban-testnet.stellar.org
ALLOW_INSECURE_RPC=true
START_LEDGER=0
PORT=3000
RUST_LOG=info
ENVIRONMENT=development
ALLOWED_ORIGINS=*
DB_MAX_CONNECTIONS=10
DB_MIN_CONNECTIONS=2
RATE_LIMIT_PER_MINUTE=0
EOF
  success ".env created"
else
  info ".env already exists — skipping"
fi

# ── 2. Wait for PostgreSQL ────────────────────────────────────────────────────
info "Waiting for PostgreSQL to be ready…"
MAX_ATTEMPTS=30
ATTEMPT=0
until pg_isready -h db -U soroban -d soroban_pulse -q 2>/dev/null; do
  ATTEMPT=$((ATTEMPT + 1))
  if [ "$ATTEMPT" -ge "$MAX_ATTEMPTS" ]; then
    error "PostgreSQL did not become ready after ${MAX_ATTEMPTS} attempts."
    error "Is the db service running? Try: docker compose up db"
    exit 1
  fi
  sleep 2
done
success "PostgreSQL is ready"

# ── 3. Run migrations ─────────────────────────────────────────────────────────
info "Running SQLx migrations…"
export DATABASE_URL="postgres://soroban:soroban@db:5432/soroban_pulse"

if cargo sqlx migrate run 2>&1; then
  success "Migrations applied"
else
  warn "Migration command failed — attempting with sqlx-cli directly"
  if sqlx migrate run --database-url "$DATABASE_URL" 2>&1; then
    success "Migrations applied via sqlx-cli"
  else
    error "Migrations failed. Check the output above."
    exit 1
  fi
fi

# ── 4. Seed development data ──────────────────────────────────────────────────
info "Seeding development data with realistic demo events…"

# Use the Rust seed binary for a richer, realistic dataset.
# SEED_EVENTS can be overridden (e.g. export SEED_EVENTS=1000) before
# running postCreate.sh to get a larger dataset.
SEED_EVENTS="${SEED_EVENTS:-200}"

if cargo run --bin seed -- --events "$SEED_EVENTS" --database-url "$DATABASE_URL" 2>&1; then
  ROW_COUNT=$(psql -t -A "$DATABASE_URL" -c "SELECT COUNT(*) FROM events;" 2>/dev/null || echo "?")
  success "Database seeded — ${ROW_COUNT} event(s) in the events table"
else
  warn "Rust seed binary failed; falling back to minimal inline seed…"
  psql "$DATABASE_URL" <<'SQL'
INSERT INTO events (
  id, contract_id, event_type, tx_hash, ledger, "timestamp", event_data, created_at
)
VALUES
  (
    gen_random_uuid(),
    'CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4',
    'contract',
    'devtxhash000000000000000000000000000000000000000000000000000001',
    1000001,
    NOW() - INTERVAL '10 minutes',
    '{"topic":["transfer"],"value":{"i128":{"hi":0,"lo":1000000}}}',
    NOW()
  ),
  (
    gen_random_uuid(),
    'CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4',
    'contract',
    'devtxhash000000000000000000000000000000000000000000000000000002',
    1000002,
    NOW() - INTERVAL '5 minutes',
    '{"topic":["mint"],"value":{"i128":{"hi":0,"lo":500000}}}',
    NOW()
  )
ON CONFLICT DO NOTHING;
SQL
  ROW_COUNT=$(psql -t -A "$DATABASE_URL" -c "SELECT COUNT(*) FROM events;" 2>/dev/null || echo "?")
  success "Fallback seed complete — ${ROW_COUNT} event(s) in the events table"
fi

# ── 5. Node dependencies ──────────────────────────────────────────────────────
info "Installing Node dependencies for frontend…"
if [ -f frontend/package.json ]; then
  (cd frontend && npm ci --prefer-offline 2>&1 | tail -5) && \
    success "frontend/ Node modules installed"
else
  warn "frontend/package.json not found — skipping"
fi

if [ -f web/package.json ]; then
  info "Installing Node dependencies for web/…"
  (cd web && npm ci --prefer-offline 2>&1 | tail -5) && \
    success "web/ Node modules installed"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  SorobanPulse dev container is ready! 🚀${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
echo ""
echo "  Start the API:           make run"
echo "  Run tests:               make test"
echo "  Start frontend:          cd frontend && npm run dev"
echo "  Re-seed (200 events):    make seed"
echo "  Seed for perf testing:   make seed SEED_ARGS='--events 100000'"
echo "  List all make targets:   make help"
echo ""
